env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: [error, { allow: [warn, error, info, dir] }]
